
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalStorageProvider } from "./store/GlobalStorageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Stack UnOverflow",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scan-lines`}
    >
      <body className='min-h-full flex flex-col'>
        <GlobalStorageProvider>{children}</GlobalStorageProvider>
      </body>
    </html>
  );
}
